language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm
  
env:
  - DB=mysql

before_install:
  - composer self-update
  
before_script:
  - composer install --prefer-source --no-interaction

script: phpunit --verbose

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
